/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package assignment3sample.Interface;

import assignment3sample.Business.Car;
import assignment3sample.Business.CarInfoProcess;
import assignment3sample.page.CreatePage;
import assignment3sample.page.SearchPage;
import assignment3sample.page.UpdatePage;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;

/**
 *
 * @author tusiyu
 */
@SuppressWarnings("all")
public class MainFrame_1 extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private List<Car> carList;

    private CreatePage createPage;
    private SearchPage searchPage;
    private UpdatePage updatePage;

    public MainFrame_1() {
        initComponents();
        carList = CarInfoProcess.getCarList();
        for(Car c:carList)
            System.out.println(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        createPage = new CreatePage();
        searchPage = new SearchPage();
        updatePage = new UpdatePage();

        jSplitPanel = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        initRightJPanel(jPanel1);
        jSplitPanel.setRightComponent(jPanel1);

        initLeftJPanel(jPanel2);
        jSplitPanel.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPanel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void initRightJPanel(JPanel jPanel1) {
        jPanel1.setSize(500, 400);
        GridLayout gridLayout = new GridLayout(5,1);
        jPanel1.setLayout(gridLayout);

        JLabel lblAssignmentIi = new JLabel("                          ASSIGNMENT 3");
        lblAssignmentIi.setFont(new Font("Tahoma", Font.PLAIN, 20));
        jPanel1.add(lblAssignmentIi,BorderLayout.CENTER);

        JLabel lblKthRoyalInstitute = new JLabel("              Application Engineergin & Development - Fall 2019           ");
        lblKthRoyalInstitute.setFont(new Font("Tahoma", Font.PLAIN, 16));
        jPanel1.add(lblKthRoyalInstitute,BorderLayout.CENTER);
    }

    private void initLeftJPanel(JPanel jPanel2) {
        createBtn = new Button("create");
        searchBtn = new Button("search");
        updateBtn = new Button("update");

        createBtn.addActionListener(new ActionListener() {
            @SuppressWarnings("deprecation")
            public void actionPerformed(ActionEvent arg0) {
                jPanel1.setVisible(false);
                JPanel jPanel = createPage.playCreateJPanel();
                jSplitPanel.setRightComponent(jPanel);
                return;
            }
        });

        searchBtn.addActionListener(new ActionListener() {
            @SuppressWarnings("deprecation")
            public void actionPerformed(ActionEvent arg0) {
                jPanel1.setVisible(false);
                JPanel jPanel = searchPage.playSearchQuestionJPanel(jSplitPanel);
                jSplitPanel.setRightComponent(jPanel);
                return;
            }
        });

        updateBtn.addActionListener(new ActionListener() {
            @SuppressWarnings("deprecation")
            public void actionPerformed(ActionEvent arg0) {
                jPanel1.setVisible(false);
                JPanel jPanel = updatePage.playSearchJPanel(jSplitPanel);
                jSplitPanel.setRightComponent(jPanel);
                return;
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setAutoCreateGaps(true); // 自动创建组件之间的间隙
//        jPanel2Layout.setAutoCreateContainerGaps(true); // 自动创建容器与触到容器边框的组件之间的间隙
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addGap(80, 100, Short.MAX_VALUE)
                        .addComponent(createBtn)
                        .addComponent(searchBtn)
                        .addComponent(updateBtn)
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createSequentialGroup()
                        .addGap(100, 300, Short.MAX_VALUE)
                        .addComponent(createBtn)
                        .addComponent(searchBtn)
                        .addComponent(updateBtn)
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPanel;

    private Button createBtn;
    private Button searchBtn;
    private Button updateBtn;
    // End of variables declaration//GEN-END:variables

    public static void alertError(String errorMsg) {
        alert("ERROR", errorMsg);
    }

    public static void alertSuc(String msg) {
        alert("SUCCESS", msg);
    }

    public static void alert(String title, String errorMsg) {
        Dimension screen=Toolkit.getDefaultToolkit().getScreenSize();
        int screenWidth = screen.width;
        int screenHeight = screen.height;
        int jFrameWidth = screenWidth > 300 ? 300 : screenWidth;
        int jFrameHeight = screenHeight > 150 ? 150 : screenHeight;

        JFrame alertJFrame = new JFrame();
        alertJFrame.setBounds((screenWidth - jFrameWidth) / 2, (screenHeight - jFrameHeight) / 2, jFrameWidth, jFrameHeight);
        alertJFrame.setTitle(title);
        JLabel errorMsgLabel = new JLabel(errorMsg, JLabel.CENTER);
        errorMsgLabel.setFont(new Font("微软雅黑", Font.PLAIN, 13));
        alertJFrame.getContentPane().add(errorMsgLabel);
        alertJFrame.setVisible(true);
    }
}
